name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PATH="/usr/share/dotnet:$PATH"
            cd /root/nodetunnel-server
            git pull origin main
            dotnet build -c Release
            sudo systemctl restart nodetunnel